{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "1.4.30-1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "d7op3ivlb5a25cpkigot4mig7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.4.30-1.0.0-alpha04.jar",
          "url": "symbol-processing-api-1.4.30-1.0.0-alpha04.jar",
          "size": 84151,
          "sha512": "3ca5eec2b4d56a4306fb15a0349ced3262f50bae1b5984023e1220b18c37375dcaad0247297ea24ea72937e0a5e0e7aa42edac9fe489d92ced15c42dda10a9b2",
          "sha256": "6c319c718ebf4b76e05e4e4f156b276d1f7e420a31f62bcb3ce47b4117b8fe6f",
          "sha1": "6d18f7198bc7514d91fd91691fb53bace1d88cdf",
          "md5": "e031ebd31e71c7cf65d22af6f0c7a5a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.4.30-1.0.0-alpha04.jar",
          "url": "symbol-processing-api-1.4.30-1.0.0-alpha04.jar",
          "size": 84151,
          "sha512": "3ca5eec2b4d56a4306fb15a0349ced3262f50bae1b5984023e1220b18c37375dcaad0247297ea24ea72937e0a5e0e7aa42edac9fe489d92ced15c42dda10a9b2",
          "sha256": "6c319c718ebf4b76e05e4e4f156b276d1f7e420a31f62bcb3ce47b4117b8fe6f",
          "sha1": "6d18f7198bc7514d91fd91691fb53bace1d88cdf",
          "md5": "e031ebd31e71c7cf65d22af6f0c7a5a8"
        }
      ]
    }
  ]
}
