{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7276851"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "room-compiler-2.3.0.jar",
          "url": "room-compiler-2.3.0.jar",
          "size": 3606482,
          "sha512": "ac526d0859ffd8a5de01421fa2c27a1a7d3c00bde53f19f392ac233b3a175334fbb90c614b31a174ccad45ae7677b22af666290f29dc4f9585f512f9dc045396",
          "sha256": "360c2bbb65a81a4e6bf7bf170c7735a5b0250c0a38ea00fe8de5678e6d1be0d3",
          "sha1": "e110171fc6d176e9a831b2e2e01aab78e69e2fde",
          "md5": "2a424340fddf5e791ee503cf13248ad6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.4.30-1.0.0-alpha04"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.25.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.3.0.jar",
          "url": "room-compiler-2.3.0.jar",
          "size": 3606482,
          "sha512": "ac526d0859ffd8a5de01421fa2c27a1a7d3c00bde53f19f392ac233b3a175334fbb90c614b31a174ccad45ae7677b22af666290f29dc4f9585f512f9dc045396",
          "sha256": "360c2bbb65a81a4e6bf7bf170c7735a5b0250c0a38ea00fe8de5678e6d1be0d3",
          "sha1": "e110171fc6d176e9a831b2e2e01aab78e69e2fde",
          "md5": "2a424340fddf5e791ee503cf13248ad6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.3.0-sources.jar",
          "url": "room-compiler-2.3.0-sources.jar",
          "size": 407551,
          "sha512": "3e1f351715ccf981711ff1c4c6542133450efa34d18ff8d59d1acaad8feaa0c87c048562fa0c130c93aecc409ecda2dd3a5d321d019de76c9de54514ac004702",
          "sha256": "9b765251a900ffde4aabd94e3b35f8cf9a5da3211ffd3a587d2e09b530aa555f",
          "sha1": "5d9022c11a091974541b1be53a7e78cf72245ad0",
          "md5": "f0e8f857209d70b3730251af98deb0c6"
        }
      ]
    }
  ]
}
