{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7276851"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0.jar",
          "url": "room-compiler-processing-2.3.0.jar",
          "size": 588983,
          "sha512": "b86ef42eae9f420a36c819e773b7bc2aebb362505a885836a0518f519fe3480487c82ca65667a523f9090fc642ee88ef502582605ce0b78e4208edaf6c1df7d1",
          "sha256": "b7ee51fdab8bb3c594f50ac874078259e64552efa54b80ba3d24eeedd419dcfd",
          "sha1": "dad0f7771f2b17126d0ac297296214c1562f04b5",
          "md5": "0476aec649743636adfeccb80d73fe66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.4.30-1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0.jar",
          "url": "room-compiler-processing-2.3.0.jar",
          "size": 588983,
          "sha512": "b86ef42eae9f420a36c819e773b7bc2aebb362505a885836a0518f519fe3480487c82ca65667a523f9090fc642ee88ef502582605ce0b78e4208edaf6c1df7d1",
          "sha256": "b7ee51fdab8bb3c594f50ac874078259e64552efa54b80ba3d24eeedd419dcfd",
          "sha1": "dad0f7771f2b17126d0ac297296214c1562f04b5",
          "md5": "0476aec649743636adfeccb80d73fe66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-sources.jar",
          "url": "room-compiler-processing-2.3.0-sources.jar",
          "size": 126171,
          "sha512": "98e6466b6570ffa80e3270ba8ce3929cf90ffbb9d351325c0622d0d1ec881b57a70768e8da085f8ac2b748aaf6b51d01cf787cf85318dba8ccf27b92b0c6df1a",
          "sha256": "065678897899560a7ddc3544e5edafab0e33d9342770e194ad1cb519ef30dffb",
          "sha1": "c9ca270382d6bd7fc9470acbadc1314dff5314e5",
          "md5": "431bf0c6d7a6e129fcc82a5d14793375"
        }
      ]
    }
  ]
}
